item {
  id: 1
  name: 'a'
}

item {
  id: 2
  name: 'n'
}

item {
  id: 3
  name: 'c'
}

item {
  id: 4
  name: 'r'
}

item {
  id: 5
  name: 'k'
}

item {
  id: 6
  name: 'f'
}

item {
  id: 7
  name: 't'
}

item {
  id: 8
  name: 's'
}

item {
  id: 9
  name: 'w'
}

item {
  id: 10
  name: 'l'
}

item {
  id: 11
  name: 'p'
}

item {
  id: 12
  name: 'd'
}

item {
  id: 13
  name: 'j'
}

item {
  id: 14
  name: 'y'
}

item {
  id: 15
  name: 'v'
}

item {
  id: 16
  name: 'm'
}

item {
  id: 17
  name: 'g'
}

item {
  id: 18
  name: 'b'
}

item {
  id: 19
  name: 'q'
}

item {
  id: 20
  name: 'z'
}

item {
  id: 21
  name: 'H'
}

item {
  id: 22
  name: 'N'
}

item {
  id: 23
  name: 'C'
}

item {
  id: 24
  name: 'R'
}

item {
  id: 25
  name: 'K'
}

item {
  id: 26
  name: 'F'
}

item {
  id: 27
  name: 'T'
}

item {
  id: 28
  name: 'S'
}

item {
  id: 29
  name: 'W'
}

item {
  id: 30
  name: 'L'
}

item {
  id: 31
  name: 'P'
}

item {
  id: 32
  name: 'D'
}

item {
  id: 33
  name: 'J'
}

item {
  id: 34
  name: 'Y'
}

item {
  id: 35
  name: 'V'
}

item {
  id: 36
  name: 'M'
}

item {
  id: 37
  name: 'G'
}

item {
  id: 38
  name: 'B'
}

item {
  id: 39
  name: 'Q'
}

item {
  id: 40
  name: 'Z'
}

item {
  id: 41
  name: 'u'
}

item {
  id: 42
  name: 'i'
}

item {
  id: 43
  name: 'e'
}

item {
  id: 44
  name: '['
}

item {
  id: 45
  name: '{'
}

item {
  id: 46
  name: '='
}

item {
  id: 47
  name: 'h'
}

item {
  id: 48
  name: '_'
}

item {
  id: 49
  name: ']'
}

item {
  id: 50
  name: '}'
}

item {
  id: 51
  name: '-'
}

item {
  id: 52
  name: 'o'
}

